// AUTO-GENERATED by scripts/fetch-merch.mjs from the live UB Drip store
// (merch.mitmakmotors.co.za WooCommerce Store API). Re-run to refresh.

export interface MerchProduct {
  name: string;
  price: string;
  category: string;
  image: string;
  href: string;
}

export const merchStoreUrl = 'https://merch.mitmakmotors.co.za/';

export const merchProducts: MerchProduct[] = [
  {
    "name": "Anarra Level Corduroy Cap",
    "price": "R460",
    "category": "Caps",
    "image": "/merch/anarra-level-corduroy-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/anarra-level-corduroy-cap/"
  },
  {
    "name": "Phone Case",
    "price": "R250",
    "category": "Phone Case",
    "image": "/merch/adventure-tough-phone-case-pvc.png",
    "href": "https://merch.mitmakmotors.co.za/product/adventure-tough-phone-case-pvc/"
  },
  {
    "name": "Lion’s Roar T-Shirt",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/lions-roar-t-shirt.png",
    "href": "https://merch.mitmakmotors.co.za/product/lions-roar-t-shirt/"
  },
  {
    "name": "UB Drip Embroidery",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/ub-drip-embroidery.png",
    "href": "https://merch.mitmakmotors.co.za/product/ub-drip-embroidery/"
  },
  {
    "name": "UB Drip White Cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/ub-drip-white-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/ub-drip-white-cap/"
  },
  {
    "name": "UB Drip Trucker Cap",
    "price": "R397",
    "category": "Caps",
    "image": "/merch/ub-drip-trucker-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/ub-drip-trucker-cap/"
  },
  {
    "name": "UB Air-Tech Sky-Blue cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/ub-air-tech-sky-blue-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/ub-air-tech-sky-blue-cap/"
  },
  {
    "name": "Mit-Mak Graffiti Lanyard",
    "price": "R150",
    "category": "Rim Scratchers",
    "image": "/merch/mit-mak-graffiti-key-chain.png",
    "href": "https://merch.mitmakmotors.co.za/product/mit-mak-graffiti-key-chain/"
  },
  {
    "name": "ANARRA LEVEL! Short Sleeve Female Cut",
    "price": "R329.50",
    "category": "Rim Scratchers",
    "image": "/merch/anarra-level-short-sleeve.png",
    "href": "https://merch.mitmakmotors.co.za/product/anarra-level-short-sleeve/"
  },
  {
    "name": "Adventure Tough Girl T-Shirt",
    "price": "R329.50",
    "category": "Rim Scratchers",
    "image": "/merch/adventure-tough-girl-t-shirt.png",
    "href": "https://merch.mitmakmotors.co.za/product/adventure-tough-girl-t-shirt/"
  },
  {
    "name": "Be A Man Salute Belt",
    "price": "R1500",
    "category": "Uncle Bobby Humour",
    "image": "/merch/be-a-man-salute-belt-copy.png",
    "href": "https://merch.mitmakmotors.co.za/product/be-a-man-salute-belt-copy/"
  },
  {
    "name": "Be A Man Shap Belt",
    "price": "R1500",
    "category": "Uncle Bobby Humour",
    "image": "/merch/be-a-man-shap-belt.png",
    "href": "https://merch.mitmakmotors.co.za/product/be-a-man-shap-belt/"
  },
  {
    "name": "Strong Mind, Body And Wallet sweats",
    "price": "R1300",
    "category": "No Excuses Gear",
    "image": "/merch/strong-mind-body-and-wallet-sweats.png",
    "href": "https://merch.mitmakmotors.co.za/product/strong-mind-body-and-wallet-sweats/"
  },
  {
    "name": "Strong Mind, Body And Wallet T-Shirt",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/strong-mind-body-and-wallet-t-shirt.png",
    "href": "https://merch.mitmakmotors.co.za/product/strong-mind-body-and-wallet-t-shirt/"
  },
  {
    "name": "Lion’s Mindset T-Shirt",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/lions-mindset-t-shirt-copy.png",
    "href": "https://merch.mitmakmotors.co.za/product/lions-mindset-t-shirt-copy/"
  },
  {
    "name": "Respect Is Earned T-Shirt",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/respect-is-earned-t-shirt.png",
    "href": "https://merch.mitmakmotors.co.za/product/respect-is-earned-t-shirt/"
  },
  {
    "name": "Lion’s Mindset Hoodie",
    "price": "R1500",
    "category": "No Excuses Gear",
    "image": "/merch/lions-mindset-hoodie.png",
    "href": "https://merch.mitmakmotors.co.za/product/lions-mindset-hoodie/"
  },
  {
    "name": "Unbreakable hoodie",
    "price": "R1500",
    "category": "No Excuses Gear",
    "image": "/merch/unbreakable-hoodie.png",
    "href": "https://merch.mitmakmotors.co.za/product/unbreakable-hoodie/"
  },
  {
    "name": "Outsmart Everyone Hoodie",
    "price": "R1500",
    "category": "No Excuses Gear",
    "image": "/merch/outsmart-everyone-hoodie.png",
    "href": "https://merch.mitmakmotors.co.za/product/outsmart-everyone-hoodie/"
  },
  {
    "name": "Uncle Bobby Too Cool Track Jacket",
    "price": "R1500",
    "category": "Rim Scratchers",
    "image": "/merch/uncle-bobby-too-cool-track-jacket.png",
    "href": "https://merch.mitmakmotors.co.za/product/uncle-bobby-too-cool-track-jacket/"
  },
  {
    "name": "UB Track Jacket",
    "price": "R1500",
    "category": "Uncle Bobby Humour",
    "image": "/merch/ub-track-jacket-copy.png",
    "href": "https://merch.mitmakmotors.co.za/product/ub-track-jacket-copy/"
  },
  {
    "name": "Uncle Bobby’s Track Jacket",
    "price": "R1500",
    "category": "Uncle Bobby Humour",
    "image": "/merch/uncle-bobbys-track-jacket.png",
    "href": "https://merch.mitmakmotors.co.za/product/uncle-bobbys-track-jacket/"
  },
  {
    "name": "bobby Is My Hobby Socks",
    "price": "R150",
    "category": "Uncle Bobby Humour",
    "image": "/merch/bobby-is-my-hobby-socks.png",
    "href": "https://merch.mitmakmotors.co.za/product/bobby-is-my-hobby-socks/"
  },
  {
    "name": "Rimscratcher Socks",
    "price": "R150",
    "category": "Rim Scratchers",
    "image": "/merch/rimscratcher-socks.png",
    "href": "https://merch.mitmakmotors.co.za/product/rimscratcher-socks/"
  },
  {
    "name": "Noise Lady shirt",
    "price": "R429.50",
    "category": "Rim Scratchers",
    "image": "/merch/noise-lady-shirt.png",
    "href": "https://merch.mitmakmotors.co.za/product/noise-lady-shirt/"
  },
  {
    "name": "Unbreakable Mindset T-Shirt - Female",
    "price": "R429.50",
    "category": "Rim Scratchers",
    "image": "/merch/unbreakable-mindset.png",
    "href": "https://merch.mitmakmotors.co.za/product/unbreakable-mindset/"
  },
  {
    "name": "It’s A Boy Cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/its-a-boy-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/its-a-boy-cap/"
  },
  {
    "name": "Rimscratcher Graffiti Cap",
    "price": "R600",
    "category": "Caps",
    "image": "/merch/rimscratcher-graffiti-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/rimscratcher-graffiti-cap/"
  },
  {
    "name": "Cheese Boy Cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/cheese-boy-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/cheese-boy-cap/"
  },
  {
    "name": "Full On Drug Dealer Cap - Cool Dog Edition",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/full-on-drug-dealer-cap-cool-dog-edition.png",
    "href": "https://merch.mitmakmotors.co.za/product/full-on-drug-dealer-cap-cool-dog-edition/"
  },
  {
    "name": "UB Blue Print Cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/ub-blue-print-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/ub-blue-print-cap/"
  },
  {
    "name": "Full-on Drug Dealer Cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/full-on-drug-dealer-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/full-on-drug-dealer-cap/"
  },
  {
    "name": "Rimscratcher - Trucker Levell",
    "price": "R600",
    "category": "Caps",
    "image": "/merch/stupid-low-cap.png",
    "href": "https://merch.mitmakmotors.co.za/product/stupid-low-cap/"
  },
  {
    "name": "Stupid low cap",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/stupid-low-cap-2.png",
    "href": "https://merch.mitmakmotors.co.za/product/stupid-low-cap-2/"
  },
  {
    "name": "UB Drip - Say it in Pink!",
    "price": "R300",
    "category": "Caps",
    "image": "/merch/ub-drip-say-it-in-pink.jpeg",
    "href": "https://merch.mitmakmotors.co.za/product/ub-drip-say-it-in-pink/"
  },
  {
    "name": "Tune Tune Baboon - Pink Female",
    "price": "R340",
    "category": "Rim Scratchers",
    "image": "/merch/tune-tune-baboon-pink-female.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/tune-tune-baboon-pink-female/"
  },
  {
    "name": "Anarra Level Shirt - Female",
    "price": "R340",
    "category": "Rim Scratchers",
    "image": "/merch/anarra-level-shirt-female.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/anarra-level-shirt-female/"
  },
  {
    "name": "Mug - Outwork, Outperform, Outsmart, Outlast",
    "price": "R220",
    "category": "Mug",
    "image": "/merch/mug-outwork-outperform-outsmart-outlast.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/mug-outwork-outperform-outsmart-outlast/"
  },
  {
    "name": "Mug - Noice",
    "price": "R220",
    "category": "Mug",
    "image": "/merch/mug-noice.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/mug-noice/"
  },
  {
    "name": "Mug - Anarra Level",
    "price": "R220",
    "category": "Mug",
    "image": "/merch/mug-anarra-level.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/mug-anarra-level/"
  },
  {
    "name": "Mug - Rimscratcher",
    "price": "R220",
    "category": "Mug",
    "image": "/merch/mug-rimscratcher.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/mug-rimscratcher/"
  },
  {
    "name": "Stuupid Low Shirt - Slim Fit",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/stuupid-low-shirt.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/stuupid-low-shirt/"
  },
  {
    "name": "Unbreakable Mindset - No Excuses Gear",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/unbreakable-mindset-no-excuses-gear.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/unbreakable-mindset-no-excuses-gear/"
  },
  {
    "name": "Rimscratcher Cap",
    "price": "R250",
    "category": "Caps",
    "image": "/merch/rimscratcher-cap.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/rimscratcher-cap/"
  },
  {
    "name": "Anarra Level Shirt",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/anarra-level-shirt.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/anarra-level-shirt/"
  },
  {
    "name": "Anarra Level! - Trucker Cap",
    "price": "R250",
    "category": "Caps",
    "image": "/merch/anarra-level-trucker-cap.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/anarra-level-trucker-cap/"
  },
  {
    "name": "Slim Fit Gym Fit - Uncle Bobby Shirt",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/slim-fit-gym-fit-uncle-bobby-shirt.jpeg",
    "href": "https://merch.mitmakmotors.co.za/product/slim-fit-gym-fit-uncle-bobby-shirt/"
  },
  {
    "name": "Graffiti What Kind - Mug",
    "price": "R220",
    "category": "Mug",
    "image": "/merch/graffiti-what-kind-mug.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/graffiti-what-kind-mug/"
  },
  {
    "name": "Bucket Hat Spotty - Don’t Panic Just Look Up",
    "price": "R220",
    "category": "Caps",
    "image": "/merch/bucket-hat-yellow-spotty-dont-panic-just-look-up.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/bucket-hat-yellow-spotty-dont-panic-just-look-up/"
  },
  {
    "name": "Tottie Doppie - It’s a Boy",
    "price": "R150",
    "category": "Uncle Bobby Humour",
    "image": "/merch/tottie-doppie-its-a-boy.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/tottie-doppie-its-a-boy/"
  },
  {
    "name": "Sunny South Africa- Men",
    "price": "R450",
    "category": "Uncle Bobby Humour",
    "image": "/merch/sunny-south-africa-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/sunny-south-africa-men/"
  },
  {
    "name": "Al My Geld - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/al-my-geld-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/al-my-geld-men/"
  },
  {
    "name": "Kies Tussen ‘n Goeie vrou en ‘n Bakkie - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/kies-tussen-n-goeie-vrou-en-n-bakkie-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/kies-tussen-n-goeie-vrou-en-n-bakkie-men/"
  },
  {
    "name": "Blessed From Above - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/blessed-from-above-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/blessed-from-above-men/"
  },
  {
    "name": "Tune Tune Baboon - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/tune-tune-baboon-men.png",
    "href": "https://merch.mitmakmotors.co.za/product/tune-tune-baboon-men/"
  },
  {
    "name": "Uncle Bobby Out Soft-Shell Hoodie-Men",
    "price": "R1500",
    "category": "Uncle Bobby Humour",
    "image": "/merch/uncle-bobby-out-soft-shell-hoodie-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/uncle-bobby-out-soft-shell-hoodie-men/"
  },
  {
    "name": "Buy A Belt Be The Man Of The House - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/buy-a-belt-be-the-man-of-the-house-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/buy-a-belt-be-the-man-of-the-house-men/"
  },
  {
    "name": "What’s Cutting - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/bmw-men-copy.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/bmw-men-copy/"
  },
  {
    "name": "BMW - Men",
    "price": "R430",
    "category": "Mit-Mak Motors",
    "image": "/merch/bmw-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/bmw-men/"
  },
  {
    "name": "Outwork, Outperform, Outsmart, Outlast- Men",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/outwork-outperform-outsmart-outlast-men.png",
    "href": "https://merch.mitmakmotors.co.za/product/outwork-outperform-outsmart-outlast-men/"
  },
  {
    "name": "Full On! Drug Dealer Tint - Ladies",
    "price": "R350",
    "category": "Rim Scratchers",
    "image": "/merch/full-on-drug-dealer-tint-ladies.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/full-on-drug-dealer-tint-ladies/"
  },
  {
    "name": "Future Rim Scratcher -Kiddies",
    "price": "R280",
    "category": "Kids",
    "image": "/merch/future-rim-scratcher.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/future-rim-scratcher/"
  },
  {
    "name": "Level Up Get A BMW - Kiddies",
    "price": "R280",
    "category": "Kids",
    "image": "/merch/level-up-get-a-bmw.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/level-up-get-a-bmw/"
  },
  {
    "name": "My Dad Drives A BMW - Kiddies",
    "price": "R280",
    "category": "Kids",
    "image": "/merch/my-dad-drives-a-bmw.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/my-dad-drives-a-bmw/"
  },
  {
    "name": "Bob’s Your Uncle - Kiddies",
    "price": "R280",
    "category": "Kids",
    "image": "/merch/bobs-your-uncle.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/bobs-your-uncle/"
  },
  {
    "name": "Bob’s Your Uncle - Kiddies Tote Bag",
    "price": "R170",
    "category": "Kids",
    "image": "/merch/bobs-your-uncle-tote-bag.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/bobs-your-uncle-tote-bag/"
  },
  {
    "name": "Let Him Drive - Ladies",
    "price": "R350",
    "category": "Rim Scratchers",
    "image": "/merch/let-him-drive-ladies.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/let-him-drive-ladies/"
  },
  {
    "name": "#1 Rimscratcher Shirt - Ladies",
    "price": "R480",
    "category": "Rim Scratchers",
    "image": "/merch/1-rim-scratcher-shirt-ladies.png",
    "href": "https://merch.mitmakmotors.co.za/product/1-rim-scratcher-shirt-ladies/"
  },
  {
    "name": "Buy Your Wife A Car - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/buy-your-wife-a-car-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/buy-your-wife-a-car-men/"
  },
  {
    "name": "Bobby Is My Hobby - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/bobby-is-my-hobby-men.png",
    "href": "https://merch.mitmakmotors.co.za/product/bobby-is-my-hobby-men/"
  },
  {
    "name": "Drug Dealer Tint - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/drug-dealer-tint.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/drug-dealer-tint/"
  },
  {
    "name": "Its A Boy - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/its-a-boy-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/its-a-boy-men/"
  },
  {
    "name": "What Audi Drivers See - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/what-audi-drivers-see-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/what-audi-drivers-see-men/"
  },
  {
    "name": "Its An Old Boy - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/its-an-old-boy-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/its-an-old-boy-men/"
  },
  {
    "name": "Howzit Boss - Men",
    "price": "R430",
    "category": "Uncle Bobby Humour",
    "image": "/merch/howzit-boss-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/howzit-boss-men/"
  },
  {
    "name": "Uncle Bobby Out - Yellow Spottie Print",
    "price": "R250",
    "category": "Caps",
    "image": "/merch/uncle-bobby-out-yellow.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/uncle-bobby-out-yellow/"
  },
  {
    "name": "Uncle Bobby Out - Bobby Salute Print",
    "price": "R250",
    "category": "Caps",
    "image": "/merch/uncle-bobby-out-black.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/uncle-bobby-out-black/"
  },
  {
    "name": "No Handouts Cap - Blue",
    "price": "R250",
    "category": "Caps",
    "image": "/merch/no-handouts-cap-blue.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/no-handouts-cap-blue/"
  },
  {
    "name": "No Handouts Cap - Black",
    "price": "R320",
    "category": "Caps",
    "image": "/merch/no-handouts-cap-black.png",
    "href": "https://merch.mitmakmotors.co.za/product/no-handouts-cap-black/"
  },
  {
    "name": "Outwork Everyone - Men",
    "price": "R430",
    "category": "No Excuses Gear",
    "image": "/merch/the-only-formula-to-success-men.jpg",
    "href": "https://merch.mitmakmotors.co.za/product/the-only-formula-to-success-men/"
  }
];
