// AUTO-GENERATED by scripts/fetch-staff.mjs from the live Mit-Mak staff
// directory (portal.mitmakmotors.online/staff). Re-run the script to refresh.

export interface StaffPerson {
  name: string;
  role: string;
  image: string;
}

export interface StaffDepartment {
  title: string;
  people: StaffPerson[];
}

export const staffDepartments: StaffDepartment[] = [
  {
    "title": "Leadership",
    "people": [
      {
        "name": "Bobby Petkov",
        "role": "Group CEO",
        "image": "/staff/image_6784def8768fa8.63129354.png"
      },
      {
        "name": "Dimitri Petkov",
        "role": "Founder",
        "image": "/staff/image_67c992e675e2c6.75112940.png"
      },
      {
        "name": "Maria Petkova",
        "role": "Owner",
        "image": "/staff/image_67b38167668d89.78094480.png"
      },
      {
        "name": "Elena Petkova",
        "role": "Marketing Manager",
        "image": "/staff/image_67c9935dabaa81.25134142.png"
      }
    ]
  },
  {
    "title": "Sales Executives",
    "people": [
      {
        "name": "Eugene Beukes",
        "role": "Sales Executive",
        "image": "/staff/image_69c4ff37ec8753.73412402.png"
      },
      {
        "name": "Edward Magane",
        "role": "Sales Executive",
        "image": "/staff/image_68e61114954490.72863174.png"
      }
    ]
  },
  {
    "title": "Mit-Mak Floor 1",
    "people": [
      {
        "name": "Mahlatsi Nkoana",
        "role": "Sales Executive",
        "image": "/staff/image_6968b2160263b9.93910715.png"
      },
      {
        "name": "Joseph Malope",
        "role": "Sales Executive",
        "image": "/staff/image_67bda4dd6e8419.08757199.png"
      },
      {
        "name": "Louis Mogohlwane",
        "role": "Sales Executive",
        "image": "/staff/image_690090f87fa4a6.89172671.png"
      },
      {
        "name": "Vusumuzi Bosman",
        "role": "Sales Executive",
        "image": "/staff/image_69008fe2903d39.25913414.png"
      },
      {
        "name": "Celia Roos",
        "role": "Human Resources Manager",
        "image": "/staff/image_68e6245f85b160.94561664.png"
      },
      {
        "name": "Chikita Matjila",
        "role": "Floor Controller",
        "image": "/staff/image_67b4d6883c7fe3.17570807.png"
      },
      {
        "name": "Lawrence Sayidi",
        "role": "Cafe",
        "image": "/staff/image_67b4df6abb4eb2.89347089.png"
      },
      {
        "name": "Nhlanhla Mbele",
        "role": "Mit-Mak Cafe Chef",
        "image": "/staff/image_67b4dfd8ad9f33.94764043.png"
      }
    ]
  },
  {
    "title": "Mit-Mak Floor 2",
    "people": [
      {
        "name": "Naas Rossouw",
        "role": "Branch Manager",
        "image": "/staff/image_6784e268a23bb2.57108445.png"
      },
      {
        "name": "TT Mhangwane",
        "role": "Sales Executive",
        "image": "/staff/image_69c3b4f86ebe35.21897844.png"
      },
      {
        "name": "Peter Ndlela",
        "role": "Sales Executive",
        "image": "/staff/image_67bda570791f21.70708083.png"
      },
      {
        "name": "Heinrich du Plessis",
        "role": "Sales Executive",
        "image": "/staff/image_68e6142e9a8f38.39121374.png"
      }
    ]
  },
  {
    "title": "Mit-Mak Floor 3",
    "people": [
      {
        "name": "Armand Bester",
        "role": "Sales Executive",
        "image": "/staff/image_69008e958d7e63.03255818.png"
      },
      {
        "name": "Blessmore Chinowawa",
        "role": "Sales Executive",
        "image": "/staff/image_6900990ac0f7b4.10159120.png"
      },
      {
        "name": "Nyiko Mabasa",
        "role": "Cadet",
        "image": "/staff/image_67bda48b5348b0.26189754.png"
      }
    ]
  },
  {
    "title": "Mit-Mak Floor 4",
    "people": [
      {
        "name": "Rayno Wehmeyer",
        "role": "Branch Manager",
        "image": "/staff/image_6784e1dce335e8.89941652.png"
      },
      {
        "name": "Omphile Matsei",
        "role": "Sales Executive",
        "image": "/staff/image_69c3ad7b228f02.76025054.png"
      },
      {
        "name": "JJ Pholo",
        "role": "Sales Executive",
        "image": "/staff/image_67bda3f2216ae0.16717648.png"
      }
    ]
  },
  {
    "title": "Mit-Mak Floor 5",
    "people": [
      {
        "name": "Rendani Mafuna",
        "role": "Sales Executive",
        "image": "/staff/image_69c3a6c5e160a6.62863263.png"
      },
      {
        "name": "Keschaan Slinger",
        "role": "Sales Executive",
        "image": "/staff/image_6968b1d321a380.15050231.png"
      },
      {
        "name": "Divan Coetzee",
        "role": "Sales Executive",
        "image": "/staff/image_67bda687a02c23.01251671.png"
      }
    ]
  },
  {
    "title": "Marketing",
    "people": [
      {
        "name": "Megan Flanagan",
        "role": "Sales & Marketing Administrator",
        "image": "/staff/image_69c4ff8badc419.24398082.png"
      },
      {
        "name": "Jayden Makue",
        "role": "Marketing Assistant",
        "image": "/staff/image_69c4fff720a7e3.75933873.png"
      },
      {
        "name": "Izelme Rossouw",
        "role": "Marketing",
        "image": "/staff/image_68e627d8022c88.51040435.png"
      },
      {
        "name": "Elzie Janse van Rensburg",
        "role": "Marketing",
        "image": "/staff/image_695cf29d86f606.22807118.png"
      },
      {
        "name": "Kamohelo Tsoeli",
        "role": "Marketing Assistant",
        "image": "/staff/image_695d280ab382b8.90845613.png"
      }
    ]
  },
  {
    "title": "Buying",
    "people": [
      {
        "name": "Stefan Mostert (Mossie)",
        "role": "Buying Manager",
        "image": "/staff/image_67bdaf180f3a74.77966827.png"
      },
      {
        "name": "George Kaloianov",
        "role": "Buyer 2IC",
        "image": "/staff/image_67c71a1a245327.35874467.png"
      },
      {
        "name": "Marco da Silva",
        "role": "Buyer, Cape Town",
        "image": "/staff/image_67c841812bd869.93547382.png"
      },
      {
        "name": "Gareth Pickett",
        "role": "Buyer, Johannesburg",
        "image": "/staff/image_67c98155c492c9.50379362.png"
      },
      {
        "name": "Preva Govender",
        "role": "Buyer",
        "image": "/staff/image_67c9be0b3d6253.42125780.png"
      },
      {
        "name": "Bertie Bornman",
        "role": "Buyer",
        "image": "/staff/image_67d2b9534b7956.44768540.png"
      },
      {
        "name": "Junaid Myburgh",
        "role": "Buyer",
        "image": "/staff/image_695cf68ccb1ee6.32935872.png"
      },
      {
        "name": "Enrike Mienie",
        "role": "Buyer, Call Centre Agent",
        "image": "/staff/image_67c99e0e17cd14.55056104.png"
      },
      {
        "name": "Damian Bester",
        "role": "Buyer, Call Centre Agent",
        "image": "/staff/image_695e1610d50ab9.36702792.png"
      }
    ]
  },
  {
    "title": "Finance & Insurance",
    "people": [
      {
        "name": "Eduan Hattingh",
        "role": "Qualified F&I",
        "image": "/staff/image_6996eeb2375cb2.90979636.png"
      },
      {
        "name": "Tercia Hughes",
        "role": "F&I Signing Manager",
        "image": "/staff/image_67c6a7464d30e1.01990408.png"
      },
      {
        "name": "Charles Laine",
        "role": "Qualified F&I",
        "image": "/staff/image_67c6a9f4d1f9c0.28763864.png"
      },
      {
        "name": "Caroline Moll",
        "role": "Qualified F&I",
        "image": "/staff/image_67c6aa6c8619b9.78716071.png"
      }
    ]
  },
  {
    "title": "Finance & Insurance Assistants",
    "people": [
      {
        "name": "Megan Blom",
        "role": "Data Capturer",
        "image": "/staff/image_67d2b5f6ac0451.07549090.png"
      },
      {
        "name": "Albert Visser",
        "role": "Finance & Insurance Assistant",
        "image": "/staff/image_67c6a9dcbcf487.75467312.png"
      },
      {
        "name": "Zene Halgreen",
        "role": "Finance & Insurance Assistant",
        "image": "/staff/image_67c6aa4b921d73.24124912.png"
      },
      {
        "name": "Monique Groenewald",
        "role": "Finance & Insurance Assistant",
        "image": "/staff/image_67c6aaa46d6453.90105637.png"
      }
    ]
  },
  {
    "title": "Finances",
    "people": [
      {
        "name": "Anneke Coetzee",
        "role": "Financial Manager",
        "image": "/staff/image_68dfe21109ec48.25568100.png"
      },
      {
        "name": "Hesme Geyser",
        "role": "Administrator",
        "image": "/staff/image_6968b14a6c7d69.63071531.png"
      },
      {
        "name": "Doenell Jansen",
        "role": "Finances",
        "image": "/staff/image_67c6eabc7b99a8.50689420.png"
      },
      {
        "name": "Jacqualine Jacobs",
        "role": "Administrator",
        "image": "/staff/image_67c9915faeb0f5.64918772.png"
      }
    ]
  },
  {
    "title": "Call Centre",
    "people": [
      {
        "name": "Carmen Hartzenberg",
        "role": "Call Centre Manager",
        "image": "/staff/image_68dfebda99bd10.18944044.png"
      },
      {
        "name": "Keegan Ah-Dong",
        "role": "Call Centre Agent",
        "image": "/staff/image_6900cdb29a12d0.12962542.png"
      },
      {
        "name": "Lerato Tshotetsi",
        "role": "Call Centre Agent",
        "image": "/staff/image_6900cda92fb7e0.15952507.png"
      },
      {
        "name": "Perseverance Munyai",
        "role": "Call Centre Agent",
        "image": "/staff/image_69ce306105c938.36921083.png"
      },
      {
        "name": "Amanda Mthimunye",
        "role": "Call Centre Agent",
        "image": "/staff/image_69ce307a685d88.26292587.png"
      },
      {
        "name": "Nomsa Mkhize",
        "role": "Call Centre Agent",
        "image": "/staff/image_6900c93b26d8c6.48522852.png"
      },
      {
        "name": "Ryian Joseph",
        "role": "Call Centre Agent",
        "image": ""
      },
      {
        "name": "Monique Mariano",
        "role": "Call Centre Agent",
        "image": "/staff/image_67c6ad59a7cc30.31272501.png"
      },
      {
        "name": "Jeane Cronje",
        "role": "Call Centre Agent",
        "image": "/staff/image_67c6e6a88f31b3.89765817.png"
      },
      {
        "name": "Lucas Mfolo",
        "role": "Call Centre Agent",
        "image": "/staff/image_6900c9c1d6a374.82511887.png"
      },
      {
        "name": "Jessica Coetzer",
        "role": "Call Centre Agent",
        "image": "/staff/image_67c6e812726459.84972774.png"
      },
      {
        "name": "Michelle Venter",
        "role": "Call Centre Agent",
        "image": "/staff/image_67c6e889254366.69917402.png"
      }
    ]
  },
  {
    "title": "CRM",
    "people": [
      {
        "name": "Giselle Mc Intosh",
        "role": "CRM Supervisor",
        "image": "/staff/image_67b4d3580da3e0.03351534.png"
      },
      {
        "name": "Chenelle Bothma",
        "role": "CRM 2IC & Condition Report Administrator",
        "image": "/staff/image_67c6ed7d5ff4b9.36142479.png"
      },
      {
        "name": "Hennie Esterhuizen",
        "role": "Service Advisor",
        "image": "/staff/image_67b4d238d4ec52.33055736.png"
      },
      {
        "name": "Micheal Mabitsela",
        "role": "CRM / Workshop Driver",
        "image": "/staff/image_67b4d62dcf9f08.13169871.png"
      },
      {
        "name": "Wianka van Helsdingen",
        "role": "CRM Specialist",
        "image": "/staff/image_67c6ed3620af09.82308722.png"
      }
    ]
  },
  {
    "title": "Recon",
    "people": [
      {
        "name": "Chantel Camara",
        "role": "Recon Administrator",
        "image": "/staff/image_67b4d2725f3b40.04477060.png"
      },
      {
        "name": "Jason Britz",
        "role": "Recon Assistant",
        "image": "/staff/image_67b4d2c770ba82.17932606.png"
      },
      {
        "name": "Solomon Maisa",
        "role": "Recon: Cosmetic Parts Procurement",
        "image": "/staff/image_67bda5f42c2639.80576688.png"
      },
      {
        "name": "Zwelithini Chabalala",
        "role": "Recon: Polisher",
        "image": "/staff/image_696b3e5595d929.96287703.png"
      },
      {
        "name": "Banele Vuma",
        "role": "Recon: Polisher",
        "image": "/staff/image_67b4de97458659.07961813.png"
      }
    ]
  },
  {
    "title": "Depot & Workshop",
    "people": [
      {
        "name": "Henry Hughes",
        "role": "Manager: Depot, Recon & Workshop",
        "image": "/staff/image_67c6ebb32275c1.75297001.png"
      },
      {
        "name": "Lesedi Mokgosi",
        "role": "PDI & Workshop Operations Manager",
        "image": "/staff/image_67b4d2f64171d3.13612399.png"
      },
      {
        "name": "Rohan Swart",
        "role": "Workshop 2IC",
        "image": "/staff/image_67b4d48c2492a4.00263629.png"
      },
      {
        "name": "Siphesihle Maseko",
        "role": "Depot Receptionist",
        "image": "/staff/image_6900d03d0c8ec4.70330545.png"
      },
      {
        "name": "Pearl Ndlovu",
        "role": "Administrator",
        "image": "/staff/image_69c500249111b5.27499100.png"
      },
      {
        "name": "Carel Bekker",
        "role": "Qualified Motor Mechanic",
        "image": "/staff/image_67b4d3967d6d93.42719450.png"
      },
      {
        "name": "Mfundo Ngwenya",
        "role": "Qualified Motor Mechanic",
        "image": "/staff/image_67b73c87708421.90971948.png"
      },
      {
        "name": "Brandon Kitching",
        "role": "Parts Controller",
        "image": "/staff/image_67b4d3e12448c1.41278083.png"
      },
      {
        "name": "Jaco Groenewald",
        "role": "Workshop Technician",
        "image": "/staff/image_67b4d4179adbe6.28821174.png"
      },
      {
        "name": "Frikkie van Dyk",
        "role": "Workshop Technician",
        "image": "/staff/image_67b4d454dec0c8.82599247.png"
      },
      {
        "name": "Albert Toruvandepi",
        "role": "Workshop Technician",
        "image": "/staff/image_67b4de271586c0.35899137.png"
      },
      {
        "name": "Jan Scholtemeijer",
        "role": "Workshop Technician",
        "image": "/staff/image_67b4de5524e192.93276051.png"
      },
      {
        "name": "Evans Jani",
        "role": "Workshop Technician",
        "image": "/staff/image_67b4e3111285e4.61793799.png"
      },
      {
        "name": "Hennie Minnaar",
        "role": "Workshop Parts Driver",
        "image": "/staff/image_67b4d6bbdcfba2.35905368.png"
      },
      {
        "name": "Tumelo Nkuna",
        "role": "Cleaner",
        "image": "/staff/image_67b4e08d9c51a5.51633888.png"
      },
      {
        "name": "Alpheus Marakalala",
        "role": "Cleaner",
        "image": "/staff/image_67b4e24e12f676.91906148.png"
      },
      {
        "name": "Thabang Mathebula",
        "role": "Cleaner",
        "image": "/staff/image_67b4e41ff01b59.37689280.png"
      }
    ]
  },
  {
    "title": "Wash Bay",
    "people": [
      {
        "name": "Kurula Sithole",
        "role": "Cleaner",
        "image": "/staff/image_67cabfc9ca4eb7.24088874.png"
      },
      {
        "name": "Simon Mogoru",
        "role": "Cleaner",
        "image": "/staff/image_67cac1081f0ec0.37365764.png"
      },
      {
        "name": "Tumiso Manamela",
        "role": "Cleaner",
        "image": "/staff/image_696b2baea96af4.03119746.png"
      },
      {
        "name": "Pontsho Mashilo",
        "role": "Cleaner",
        "image": "/staff/image_696b2d74e8abd9.35190983.png"
      },
      {
        "name": "Kleinboy Rangongo",
        "role": "Cleaner",
        "image": "/staff/image_696b2ede4652d0.35725785.png"
      },
      {
        "name": "Tlhokwa Bontsi",
        "role": "Cleaner",
        "image": "/staff/image_696b3b9844b171.18874084.png"
      },
      {
        "name": "Kamogelo Mokonyane",
        "role": "Cleaner",
        "image": "/staff/image_69eb1b717a04c9.59509248.png"
      },
      {
        "name": "Kamogelo Makena",
        "role": "Cleaner",
        "image": "/staff/image_69eb1bb5ce7f98.38419084.png"
      },
      {
        "name": "Dineo Ndala",
        "role": "Cleaner",
        "image": "/staff/image_69eb1bd27d3d44.27847744.png"
      },
      {
        "name": "Tumo Mosweu",
        "role": "Cleaner",
        "image": "/staff/image_67b4e0da733c99.85869479.png"
      },
      {
        "name": "Happy Mfulwane",
        "role": "Cleaner",
        "image": "/staff/image_67b4e134dcbbe1.86403144.png"
      },
      {
        "name": "Patrick Morweng",
        "role": "Cleaner",
        "image": "/staff/image_67b4e186ab7038.90222809.png"
      },
      {
        "name": "Lizzy Ditle",
        "role": "Cleaner",
        "image": "/staff/image_67c71d24d09be7.47646114.png"
      },
      {
        "name": "Lusana Machebe",
        "role": "Cleaner",
        "image": "/staff/image_67b4e0131633c3.07382173.png"
      },
      {
        "name": "Milton Khoza",
        "role": "Cleaner",
        "image": "/staff/image_67b4e035e07c42.47753226.png"
      },
      {
        "name": "Jacob Mosia",
        "role": "Cleaner",
        "image": "/staff/image_67b4e54cb1e900.27109122.png"
      },
      {
        "name": "Ishmael Simelane",
        "role": "Cleaner",
        "image": "/staff/image_67c9959424e0b1.14581042.png"
      }
    ]
  },
  {
    "title": "Drivers",
    "people": [
      {
        "name": "Buthelezi Mpho Francis",
        "role": "Driver",
        "image": "/staff/image_696b3cc26e42b1.79897952.png"
      },
      {
        "name": "James Mojelele",
        "role": "Driver",
        "image": "/staff/image_69eb1b301679e0.74102958.png"
      },
      {
        "name": "James Manganye",
        "role": "Driver",
        "image": "/staff/image_67b4d7edf3c9c9.60269589.png"
      },
      {
        "name": "Jack Aphane",
        "role": "Driver",
        "image": "/staff/image_67b4dca6ef3880.95158542.png"
      },
      {
        "name": "Hans Strydom",
        "role": "Driver",
        "image": ""
      }
    ]
  },
  {
    "title": "Logistics",
    "people": [
      {
        "name": "Sello Mathonsi",
        "role": "Natis Controller",
        "image": "/staff/image_6968b2876f0186.15623924.png"
      },
      {
        "name": "Nikita Kelly",
        "role": "Administrator",
        "image": "/staff/image_697874a47b33b4.44756600.png"
      },
      {
        "name": "Cecilia van Staden",
        "role": "Workshop Costing Clerk, Logistics",
        "image": "/staff/image_67c6e9f17ae451.55929155.png"
      }
    ]
  },
  {
    "title": "Cadet Program",
    "people": [
      {
        "name": "Lethabo Magopa",
        "role": "Sales Executive",
        "image": "/staff/image_6900962e247807.41797405.png"
      },
      {
        "name": "Sindie Moolman",
        "role": "Cadet",
        "image": "/staff/image_6900a001bbc394.33847115.png"
      },
      {
        "name": "Vutomi Mbungana",
        "role": "Cadet",
        "image": "/staff/image_69c3a755c78b41.74528734.png"
      },
      {
        "name": "Garth Mahlakoane",
        "role": "Cadet",
        "image": "/staff/image_69c3ad002df317.26270128.png"
      },
      {
        "name": "Halle Khazamula",
        "role": "Cadet",
        "image": "/staff/image_69c3b20ed01ad3.21317136.png"
      },
      {
        "name": "Charity Nyakane",
        "role": "Cadet",
        "image": "/staff/image_69c3b22aea3be8.47080989.png"
      },
      {
        "name": "Nelson Sibiya",
        "role": "Cadet",
        "image": "/staff/image_69c3c54227da76.42022295.png"
      },
      {
        "name": "Kealeboga Ndlovu",
        "role": "Cadet",
        "image": ""
      },
      {
        "name": "Jason Louw",
        "role": "Cadet",
        "image": "/staff/image_69c3bb928f1370.76685668.png"
      },
      {
        "name": "Osego Khomo",
        "role": "Cadet",
        "image": "/staff/image_67c71b24e66073.34319150.png"
      },
      {
        "name": "Tshidiso Mogale",
        "role": "Cadet",
        "image": "/staff/image_67bdad6dd06c79.12805181.png"
      }
    ]
  },
  {
    "title": "Support",
    "people": [
      {
        "name": "Richie",
        "role": "Handyman",
        "image": "/staff/image_67b73bd0925b42.12640038.png"
      },
      {
        "name": "Klass Mofokeng",
        "role": "Security",
        "image": "/staff/image_67c995e1461f22.16013902.png"
      }
    ]
  }
];

export const staffCount = 130;
