// One-off: pull the UB Drip / Uncle Bobby merch catalogue from the live
// WooCommerce store API (names, prices, categories, sizes, colours, images,
// descriptions), download product images into public/merch/, emit data/merch.ts.
// Run: node scripts/fetch-merch.mjs
import fs from 'fs';
import path from 'path';
import https from 'https';

const API = 'https://merch.mitmakmotors.co.za/wp-json/wc/store/v1/products?per_page=100';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT = 'public/merch';
fs.mkdirSync(OUT, { recursive: true });

function get(url, binary) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { 'User-Agent': UA }, timeout: 30000 }, (r) => {
      if (r.statusCode !== 200) { r.resume(); return reject(new Error('HTTP ' + r.statusCode)); }
      if (binary) {
        const chunks = [];
        r.on('data', (c) => chunks.push(c));
        r.on('end', () => resolve(Buffer.concat(chunks)));
      } else {
        let d = '';
        r.on('data', (c) => (d += c));
        r.on('end', () => resolve(d));
      }
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('timeout')); });
  });
}

const decode = (s) =>
  String(s || '')
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(+n))
    .replace(/&#8217;|&#8216;|&#x27;/g, "'")
    .replace(/&amp;|&#038;/g, '&')
    .replace(/&#8220;|&#8221;/g, '"')
    .replace(/[–—]/g, '-')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const rand = (p) => {
  const v = parseInt(p, 10) / 100;
  return 'R' + (v % 1 === 0 ? v.toFixed(0) : v.toFixed(2));
};

const termsOf = (attrs, re) => {
  const a = (attrs || []).find((x) => re.test(x.name || ''));
  return a ? (a.terms || []).map((t) => decode(t.name)).filter(Boolean) : [];
};

const raw = JSON.parse(await get(API, false));
const products = [];
for (const x of raw) {
  const name = decode(x.name);
  const price = x.prices && x.prices.price ? rand(x.prices.price) : '';
  const category = (x.categories && x.categories[0] && decode(x.categories[0].name)) || 'Merch';
  const sizes = termsOf(x.attributes, /kids size|^\s*size\s*$/i);
  const colours = termsOf(x.attributes, /colou?r/i);
  const description = decode(x.short_description || x.description).slice(0, 320);
  const imgUrl = x.images && x.images[0] && x.images[0].src;
  let image = '';
  if (imgUrl) {
    const ext = (imgUrl.split('?')[0].match(/\.(png|jpe?g|webp)$/i) || ['.png'])[0].toLowerCase();
    const file = x.slug + ext;
    const dest = path.join(OUT, file);
    if (fs.existsSync(dest) && fs.statSync(dest).size > 1000) {
      image = '/merch/' + file;
    } else {
      try {
        const buf = await get(imgUrl, true);
        if (buf.length > 1000) { fs.writeFileSync(dest, buf); image = '/merch/' + file; }
      } catch {
        /* leave empty */
      }
    }
  }
  products.push({ name, price, category, sizes, colours, description, image });
}

const ts =
  `// AUTO-GENERATED by scripts/fetch-merch.mjs from the live UB Drip store\n` +
  `// (merch.mitmakmotors.co.za WooCommerce Store API). Re-run to refresh.\n\n` +
  `export interface MerchProduct {\n  name: string;\n  price: string;\n  category: string;\n  sizes: string[];\n  colours: string[];\n  description: string;\n  image: string;\n}\n\n` +
  `export const merchProducts: MerchProduct[] = ${JSON.stringify(products, null, 2)};\n`;
fs.writeFileSync('data/merch.ts', ts);

console.log(`products=${products.length} images_ok=${products.filter((p) => p.image).length} withSizes=${products.filter((p) => p.sizes.length).length} withColours=${products.filter((p) => p.colours.length).length}`);
